// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmKvs7tLjTLUk194h8jMrvXu0PhKZnc8A',
    appId: '1:55493381725:web:36b87d058fc9e81f16c7b4',
    messagingSenderId: '55493381725',
    projectId: 'aqar-146b6',
    authDomain: 'aqar-146b6.firebaseapp.com',
    storageBucket: 'aqar-146b6.firebasestorage.app',
    measurementId: 'G-SSHGZ9YYJR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCL-Y4qhkdOT80u7Ro1vaL9lA7idcUie3Y',
    appId: '1:55493381725:android:514946b81ac7baf516c7b4',
    messagingSenderId: '55493381725',
    projectId: 'aqar-146b6',
    storageBucket: 'aqar-146b6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkJbmkj-oqIz4rhAWh1Ysvrbs9SZY27vg',
    appId: '1:55493381725:ios:aea3632d8f9017b716c7b4',
    messagingSenderId: '55493381725',
    projectId: 'aqar-146b6',
    storageBucket: 'aqar-146b6.firebasestorage.app',
    iosBundleId: 'com.example.aqarelmasryeen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkJbmkj-oqIz4rhAWh1Ysvrbs9SZY27vg',
    appId: '1:55493381725:ios:aea3632d8f9017b716c7b4',
    messagingSenderId: '55493381725',
    projectId: 'aqar-146b6',
    storageBucket: 'aqar-146b6.firebasestorage.app',
    iosBundleId: 'com.example.aqarelmasryeen',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmKvs7tLjTLUk194h8jMrvXu0PhKZnc8A',
    appId: '1:55493381725:web:edfe77f4718f699416c7b4',
    messagingSenderId: '55493381725',
    projectId: 'aqar-146b6',
    authDomain: 'aqar-146b6.firebaseapp.com',
    storageBucket: 'aqar-146b6.firebasestorage.app',
    measurementId: 'G-HKB4DCG4CX',
  );
}
